on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Set lowercase repository name as environment variable
        run: echo "LOWER_REPO_NAME=$(echo ${{ env.FULL_REPO_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
  
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.LOWER_REPO_NAME }}:latest .
  
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ env.LOWER_REPO_NAME }}:latest
  
      - name: Set lowercase package name as environment variable
        run: echo "LOWER_PACKAGE_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        
      - name: Delete old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.LOWER_PACKAGE_NAME }}
          owner: 'kilowatt-commando'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 2
