on:
  push:
    branches: main

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/kilowatt-commando/controller-service:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/kilowatt-commando/controller-service:latest
      
    - name: Delete old packages
      uses: actions/delete-package-versions@v5
      with:
        package-name: kilowatt-commando/controller-service
        owner: 'kilowatt-commando'
        package-type: 'container'
        token: ${{ secrets.GITHUB_TOKEN }}
        min-versions-to-keep: 2
